### ISSUE TITLE
Find a way to show adopters on knative.dev main page

### ISSUE THREAD

**Issue by nainaz** [knative/community#1317] opened 2023-03-30 17:01 UTC
Logos or names of adopters on knative.dev site.
Under Trusted By

Add adopters.md under About section on site.

**Comment by nainaz** [comment] 2023-07-17 16:25
Adopters.md users displayed as projects on cncf website
https://www.cncf.io/

create this as a first issue on docs repo.

**Comment by aliok** [comment] 2023-07-17 16:26
Should have "good first issue" and "help wanted" labels

**Comment by aliok** [comment] 2023-08-14 16:38
/close

Duplicate of https://github.com/knative/community/issues/1416

**Closed by aliok** 2023-08-14 16:38 UTC
