### ISSUE TITLE
Reconcile TBD Google tech writers

### ISSUE THREAD

**Issue by mattmoor** [knative/community#101] opened 2020-02-25 21:20 UTC
I created this temporary team with elevated access to be resolved by steering: https://github.com/orgs/knative/teams/tbd-google-tech-writers/members

**Comment by vaikas** [comment] 2021-01-29 09:47
Given that @abrennan89 is the Docs WG lead, want to make sure she's looped in.
I'm honestly not clear what needs to happen here based on the description.
I see the following group:
https://github.com/orgs/knative/teams/docs-writers/members?query=membership%3Achild-team

So, I see that @abrennan89 is a member because of this:
https://github.com/orgs/knative/teams/docs-wg-leads

And the other 3 are part of the tbd-google-tech-writers.
Just trying to understand what makes the Google part necessary and not a member of say docs-writers. If somebody could clarify, then I might be able to do something about this :)

@ellenevans @RichieEscarez @carieshmarie Can you let me know what prevents us from moving to the docs-writers?

Thanks!

**Comment by mattmoor** [comment] 2021-01-29 15:04
Moving to docs-writers as what role?

**Comment by abrennan89** [comment] 2021-01-29 15:32
I'm not sure what all of this is about, but I see that Ellen and Caroline are listed in those groups. AFAIK they're not involved in Knative anymore. Richie still is but spends very limited time working on this.

**Comment by vaikas** [comment] 2021-01-29 15:48
Yeah, I just didn't have enough context from the issue description. There's a few of these issues that were created and I'm just trying to go through the backlog of serving issues and try to make headway. The way I saw it that there was couple of things at play:
 1. A group that @mattmoor created that we want to get rid off
 2. Is there a reason for this group or can the folks in that group me moved to some existing group
 3. If no, what group. If yes, why.

**Comment by mattmoor** [comment] 2021-01-29 16:03
Ack, I was sort of expecting these issues to be handled while context was a bit fresher. 😉 

The initial ACL restructure was intended to map ACLs to project roles, and these issues were opened for every deviation where folks were even mildly hesitant about losing access.

**Comment by RichieEscarez** [comment] 2021-02-01 22:55
Hey all! I'm honestly not sure what these are or how the ACLs work these days.

For context, @carieshmarie was added in the beginning to make sure someone had the privileges to cover to Sam and I. I chatted with her recently and she doesn't feel the need to keep her permissions if that means we align with the Knative org rules.  @ellenevans stepped in temporarily to help keep docs efforts going when Sam switched projects and I was away (temporarily loaned out to a priority project and then out-of-office for Carers leave).

WRT permissions. When the Knative project first started, only Sam's name was listed on the Working Groups page as the host for all community discussion and outreach but we both shared leadership responsibilities on the team. As ACLs and other things became formal, that WG host page was eventually converted into the names for each group's leadership roles and I never had feelings one way or another to have my listed as one of leads on the team (I never gave it a thought to be honest).

Therefore, I'm guessing this extra group (for elevated permissions) was created to ensure that I (and or those who help cover while i was away) maintained access to the admin tasks in knative/docs and knative/website? I still have release responsibilities and have discussed plans for changes to the docs builds (w/ Evan) so permissions to implement, test, and hopefully deploy GitHub actions would be necessary (might potentially need to provide permissions on the Netlify CLI but thats TBD). I've only just gotten over a really difficult release milestone (my internal project) so I've only just gained back more bandwidth to focus more on these projects. My plan is to resolve the pain points in the docs build and then move back into authoring content in knative/docs.

Hopefully that helps clarify what ACLs need to be preserved so that I can keep contributing on the docs side.

**Comment by vaikas** [comment] 2021-02-02 10:35
Thanks for the details. We have "Knative Release Leads" that currently rotates two people into it for every release and is a member of Knative Admin group. Sounds like the tasks / permissions that are still required for @RichieEscarez center around release responsibilities (iiuc?), and therefore is the "third release" lead that does not currently rotate? If those things are true, then I'd like to propose the following:

1. Remove the tbd-google-writers group alltogether
2. Add @RichieEscarez to the "Knative Release Leads"
   => This would (iiuc) make it consistent with other repos.

Just trying to find ways to chip away at this :)

@mattmoor to see if that would address the original issue created and @RichieEscarez and @evankanderson for making sure they are in the loop.

**Comment by mattmoor** [comment] 2021-02-02 16:35
I'd open a new issue assigned to @RichieEscarez to sort out how to make docs/website releases a rotation, and `TODO(#1234)` that issue next to his name in the release leads.  That at least gets this off of Steering's backlog 🎉 , but captures the work that's left to close this out.

@RichieEscarez bear in mind that release leads basically have org-wide super powers, so you will need to be even more careful than before (great power, great responsibility etc 😉  )

**Comment by vaikas** [comment] 2021-02-02 17:18
@mattmoor sounds like a plan (I should have explicitly called out the creation of the issue to track the rotation :) )
@RichieEscarez does this sound good to you? If so, I'll do this tmw.

**Comment by RichieEscarez** [comment] 2021-02-02 18:19
Thank @mattmoor and @vaikas!

This sounds good to me. Ill make sure not to accidentally break anything and won't venture outside of the /docs or /website repos!

**Comment by vaikas** [comment] 2021-02-04 09:02
/assign @chizhg 
/assign @evankanderson 

This has the same problem as with #91 in that the changes were made but the github members / teams were not modified. Does not look like peribolos is removing anything. Is it configured to not remove items?

**Comment by vaikas** [comment] 2021-02-04 10:47
Verified the team is no longer there:
https://github.com/orgs/knative/teams/tbd-google-tech-writers/members

The root cause was bad config that failed silently as a result of #425
Created: https://github.com/knative/test-infra/issues/2652

**Closed by vaikas** 2021-02-04 10:47 UTC
